---
id: redmine-osaka-17
base_name: utilize-redmine-by-full-text-search
tags:
- rabbit
- groonga
- mroonga
- pgroonga
- redmine
- full-text-search
presentation_date: 2017-08-26
version: 2017.8.26.2
licenses:
- CC-BY-SA-4.0
- CC-BY-3.0
slideshare_id: redmineosaka17
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: 
